import {type RouteConfig} from '@react-router/dev/routes';

const routes: RouteConfig = [
  {path: '/', file: 'routes/_index.tsx'},
  {path: 'create', file: 'routes/create.tsx'},
  {path: 'about', file: 'routes/about.tsx'},
  {path: 'collection', file: 'routes/collection._index.tsx'},
  {path: 'collection/:handle', file: 'routes/collection.$handle.tsx'},
  {path: 'product/:handle', file: 'routes/product.$handle.tsx'},
  {path: 'products/:handle', file: 'routes/products.$handle.tsx'},
  {path: 'collections', file: 'routes/collections._index.tsx'},
  {path: 'collections/:handle', file: 'routes/collections.$handle.tsx'},
  {path: 'cart', file: 'routes/cart.tsx'},
  {path: 'search', file: 'routes/search.tsx'},
  {path: 'pages/:handle', file: 'routes/pages.$handle.tsx'},
  {path: 'drops', file: 'routes/drops._index.tsx'},
  {path: 'drops/:handle', file: 'routes/drops.$handle.tsx'},
  {path: 'artists', file: 'routes/artists._index.tsx'},
  {path: 'artists/:handle', file: 'routes/artists.$handle.tsx'},
  {path: 'blog/drops', file: 'routes/blog.drops._index.tsx'},
  {path: 'blog/drops/:handle', file: 'routes/blog.drops.$handle.tsx'},
  {path: 'account', file: 'routes/account.tsx'},
  {path: 'account/login', file: 'routes/account.login.tsx'},
  {path: 'account/orders', file: 'routes/account.orders.tsx'},
  {path: 'account/authorize', file: 'routes/account.authorize.tsx'},
  {path: 'account/orders/:orderId', file: 'routes/account.orders.$orderId.tsx'},
  {path: 'policies/:policyHandle', file: 'routes/policies.$policyHandle.tsx'},
  {path: 'api/contact-capture', file: 'routes/api.contact-capture.ts'},
  {path: 'api/preview', file: 'routes/api.preview.ts'},
  {
    path: '.well-known/appspecific/com.chrome.devtools.json',
    file: 'routes/chrome-devtools-json.tsx',
  },
  {path: 'robots.txt', file: 'routes/robots.txt.tsx'},
  {path: 'sitemap', file: 'routes/sitemap.tsx'},
  {path: 'sitemap.xml', file: 'routes/sitemap.xml.tsx'},
  {path: 'components', file: 'routes/components.tsx'},
  {path: 'design-system', file: 'routes/design-system.tsx'},
];

export default routes;
