// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/create": {
    params: {};
  };
  "/product/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/collections": {
    params: {};
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/drops": {
    params: {};
  };
  "/drops/:handle": {
    params: {
      "handle": string;
    };
  };
  "/artists": {
    params: {};
  };
  "/artists/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account": {
    params: {};
  };
  "/account/login": {
    params: {};
  };
  "/account/orders": {
    params: {};
  };
  "/account/authorize": {
    params: {};
  };
  "/account/orders/:orderId": {
    params: {
      "orderId": string;
    };
  };
  "/account/recover": {
    params: {};
  };
  "/policies/:policyHandle": {
    params: {
      "policyHandle": string;
    };
  };
  "/api/preview": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/sitemap": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/create" | "/product/:handle" | "/products/:handle" | "/collections" | "/collections/:handle" | "/cart" | "/search" | "/pages/:handle" | "/drops" | "/drops/:handle" | "/artists" | "/artists/:handle" | "/account" | "/account/login" | "/account/orders" | "/account/authorize" | "/account/orders/:orderId" | "/account/recover" | "/policies/:policyHandle" | "/api/preview" | "/.well-known/appspecific/com.chrome.devtools.json" | "/robots.txt" | "/sitemap" | "/sitemap.xml";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/create.tsx": {
    id: "routes/create";
    page: "/create";
  };
  "routes/product.$handle.tsx": {
    id: "routes/product.$handle";
    page: "/product/:handle";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/collections._index.tsx": {
    id: "routes/collections._index";
    page: "/collections";
  };
  "routes/collections.$handle.tsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/pages.$handle.tsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/drops._index.tsx": {
    id: "routes/drops._index";
    page: "/drops";
  };
  "routes/drops.$handle.tsx": {
    id: "routes/drops.$handle";
    page: "/drops/:handle";
  };
  "routes/artists._index.tsx": {
    id: "routes/artists._index";
    page: "/artists";
  };
  "routes/artists.$handle.tsx": {
    id: "routes/artists.$handle";
    page: "/artists/:handle";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account";
  };
  "routes/account.login.tsx": {
    id: "routes/account.login";
    page: "/account/login";
  };
  "routes/account.orders.tsx": {
    id: "routes/account.orders";
    page: "/account/orders";
  };
  "routes/account.authorize.tsx": {
    id: "routes/account.authorize";
    page: "/account/authorize";
  };
  "routes/account.orders.$orderId.tsx": {
    id: "routes/account.orders.$orderId";
    page: "/account/orders/:orderId";
  };
  "routes/account.recover.tsx": {
    id: "routes/account.recover";
    page: "/account/recover";
  };
  "routes/policies.$policyHandle.tsx": {
    id: "routes/policies.$policyHandle";
    page: "/policies/:policyHandle";
  };
  "routes/api.preview.ts": {
    id: "routes/api.preview";
    page: "/api/preview";
  };
  "routes/chrome-devtools-json.tsx": {
    id: "routes/chrome-devtools-json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/robots.txt.tsx": {
    id: "routes/robots.txt";
    page: "/robots.txt";
  };
  "routes/sitemap.tsx": {
    id: "routes/sitemap";
    page: "/sitemap";
  };
  "routes/sitemap.xml.tsx": {
    id: "routes/sitemap.xml";
    page: "/sitemap.xml";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/create": typeof import("./app/routes/create.tsx");
  "routes/product.$handle": typeof import("./app/routes/product.$handle.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/collections._index": typeof import("./app/routes/collections._index.tsx");
  "routes/collections.$handle": typeof import("./app/routes/collections.$handle.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/pages.$handle": typeof import("./app/routes/pages.$handle.tsx");
  "routes/drops._index": typeof import("./app/routes/drops._index.tsx");
  "routes/drops.$handle": typeof import("./app/routes/drops.$handle.tsx");
  "routes/artists._index": typeof import("./app/routes/artists._index.tsx");
  "routes/artists.$handle": typeof import("./app/routes/artists.$handle.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/account.login": typeof import("./app/routes/account.login.tsx");
  "routes/account.orders": typeof import("./app/routes/account.orders.tsx");
  "routes/account.authorize": typeof import("./app/routes/account.authorize.tsx");
  "routes/account.orders.$orderId": typeof import("./app/routes/account.orders.$orderId.tsx");
  "routes/account.recover": typeof import("./app/routes/account.recover.tsx");
  "routes/policies.$policyHandle": typeof import("./app/routes/policies.$policyHandle.tsx");
  "routes/api.preview": typeof import("./app/routes/api.preview.ts");
  "routes/chrome-devtools-json": typeof import("./app/routes/chrome-devtools-json.tsx");
  "routes/robots.txt": typeof import("./app/routes/robots.txt.tsx");
  "routes/sitemap": typeof import("./app/routes/sitemap.tsx");
  "routes/sitemap.xml": typeof import("./app/routes/sitemap.xml.tsx");
};